version: '3.8'

services:
  container1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  container2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

  container3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5000"

  nginx:
    image: nginx:latest
    ports:
      - "8066:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - container1
      - container2
      - container3