events {}

http {
    include       mime.types;

    upstream container_info_app {
        ip_hash;
        server container1:5000;
        server container2:5000;
        server container3:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://container_info_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}